{% set name = "kedro-static-viz" %}
{% set version = "0.1.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: a3ff989bddb0fb8f0d2927a7c94e34a7d3ce80fce05a8524f40a28a058e422a8

build:
  number: 0
  noarch: python
  entry_points:
    - kedro-static-viz = kedro_static_viz.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - click
    - kedro
    - kedro-viz
    - python

test:
  imports:
    - kedro_static_viz
  commands:
    - pip check
    - kedro-static-viz --help
  requires:
    - pip

about:
  home: https://pypi.org/project/kedro-static-viz/
  summary: Creates a static visualization of your pipeline
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - WaylonWalker
